// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

#pragma warning disable CS1591,CS1573,CS0465,CS0649,CS8019,CS1570,CS1584,CS1658,CS0436,CS8981
using global::System;
using global::System.Diagnostics;
using global::System.Diagnostics.CodeAnalysis;
using global::System.Runtime.CompilerServices;
using global::System.Runtime.InteropServices;
using global::System.Runtime.Versioning;
using winmdroot = global::Windows.Win32;
namespace Windows.Win32
{
    namespace System.JobObjects
    {
        [Flags]
       // [global::System.CodeDom.Compiler.GeneratedCode("Microsoft.Windows.CsWin32", "0.2.104-beta+6d86f35b75")]
        internal enum JOB_OBJECT_LIMIT : uint
        {
            JOB_OBJECT_LIMIT_WORKINGSET = 0x00000001,
            JOB_OBJECT_LIMIT_PROCESS_TIME = 0x00000002,
            JOB_OBJECT_LIMIT_JOB_TIME = 0x00000004,
            JOB_OBJECT_LIMIT_ACTIVE_PROCESS = 0x00000008,
            JOB_OBJECT_LIMIT_AFFINITY = 0x00000010,
            JOB_OBJECT_LIMIT_PRIORITY_CLASS = 0x00000020,
            JOB_OBJECT_LIMIT_PRESERVE_JOB_TIME = 0x00000040,
            JOB_OBJECT_LIMIT_SCHEDULING_CLASS = 0x00000080,
            JOB_OBJECT_LIMIT_PROCESS_MEMORY = 0x00000100,
            JOB_OBJECT_LIMIT_JOB_MEMORY = 0x00000200,
            JOB_OBJECT_LIMIT_JOB_MEMORY_HIGH = 0x00000200,
            JOB_OBJECT_LIMIT_DIE_ON_UNHANDLED_EXCEPTION = 0x00000400,
            JOB_OBJECT_LIMIT_BREAKAWAY_OK = 0x00000800,
            JOB_OBJECT_LIMIT_SILENT_BREAKAWAY_OK = 0x00001000,
            JOB_OBJECT_LIMIT_KILL_ON_JOB_CLOSE = 0x00002000,
            JOB_OBJECT_LIMIT_SUBSET_AFFINITY = 0x00004000,
            JOB_OBJECT_LIMIT_JOB_MEMORY_LOW = 0x00008000,
            JOB_OBJECT_LIMIT_JOB_READ_BYTES = 0x00010000,
            JOB_OBJECT_LIMIT_JOB_WRITE_BYTES = 0x00020000,
            JOB_OBJECT_LIMIT_RATE_CONTROL = 0x00040000,
            JOB_OBJECT_LIMIT_CPU_RATE_CONTROL = 0x00040000,
            JOB_OBJECT_LIMIT_IO_RATE_CONTROL = 0x00080000,
            JOB_OBJECT_LIMIT_NET_RATE_CONTROL = 0x00100000,
            JOB_OBJECT_LIMIT_VALID_FLAGS = 0x0007FFFF,
            JOB_OBJECT_BASIC_LIMIT_VALID_FLAGS = 0x000000FF,
            JOB_OBJECT_EXTENDED_LIMIT_VALID_FLAGS = 0x00007FFF,
            JOB_OBJECT_NOTIFICATION_LIMIT_VALID_FLAGS = 0x001F8204,
        }
    }
}
