// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

#pragma warning disable CS1591,CS1573,CS0465,CS0649,CS8019,CS1570,CS1584,CS1658,CS0436,CS8981
using global::System;
using global::System.Diagnostics;
using global::System.Diagnostics.CodeAnalysis;
using global::System.Runtime.CompilerServices;
using global::System.Runtime.InteropServices;
using global::System.Runtime.Versioning;
using winmdroot = global::Windows.Win32;
namespace Windows.Win32
{
    namespace System.JobObjects
    {
        /// <summary>Contains basic and extended limit information for a job object.</summary>
        /// <remarks>
        /// <para>The system tracks the value of <b>PeakProcessMemoryUsed</b> and <b>PeakJobMemoryUsed</b> constantly. This allows you know the peak memory usage of each job. You can use this information to establish a memory limit using the <b>JOB_OBJECT_LIMIT_PROCESS_MEMORY</b> or <b>JOB_OBJECT_LIMIT_JOB_MEMORY</b> value. Note that the job memory and process memory limits are very similar in operation, but they are independent. You could set a job-wide limit of 100 MB with a per-process limit of 10 MB. In this scenario, no single process could commit more than 10 MB, and the set of processes associated with a job could never exceed 100 MB. To register for notifications  that a job has exceeded its peak memory limit while allowing processes to continue to commit memory, use the <a href="https://docs.microsoft.com/windows/desktop/api/jobapi2/nf-jobapi2-setinformationjobobject">SetInformationJobObject</a> function with the <b>JobObjectNotificationLimitInformation</b> information class.</para>
        /// <para><see href="https://docs.microsoft.com/windows/win32/api//winnt/ns-winnt-jobobject_extended_limit_information#">Read more on docs.microsoft.com</see>.</para>
        /// </remarks>
       // [global::System.CodeDom.Compiler.GeneratedCode("Microsoft.Windows.CsWin32", "0.2.104-beta+6d86f35b75")]
        internal partial struct JOBOBJECT_EXTENDED_LIMIT_INFORMATION
        {
            /// <summary>
            /// <para>A <a href="https://docs.microsoft.com/windows/desktop/api/winnt/ns-winnt-jobobject_basic_limit_information">JOBOBJECT_BASIC_LIMIT_INFORMATION</a> structure that contains basic limit information.</para>
            /// <para><see href="https://docs.microsoft.com/windows/win32/api//winnt/ns-winnt-jobobject_extended_limit_information#members">Read more on docs.microsoft.com</see>.</para>
            /// </summary>
            internal winmdroot.System.JobObjects.JOBOBJECT_BASIC_LIMIT_INFORMATION BasicLimitInformation;
            /// <summary>Reserved.</summary>
            internal winmdroot.System.Threading.IO_COUNTERS IoInfo;
            /// <summary>
            /// <para>If the <b>LimitFlags</b> member of the <a href="https://docs.microsoft.com/windows/desktop/api/winnt/ns-winnt-jobobject_basic_limit_information">JOBOBJECT_BASIC_LIMIT_INFORMATION</a> structure specifies the <b>JOB_OBJECT_LIMIT_PROCESS_MEMORY</b> value, this member specifies the limit for the virtual memory that can be committed by a process. Otherwise, this member is ignored.</para>
            /// <para><see href="https://docs.microsoft.com/windows/win32/api//winnt/ns-winnt-jobobject_extended_limit_information#members">Read more on docs.microsoft.com</see>.</para>
            /// </summary>
            internal UIntPtr ProcessMemoryLimit;
            /// <summary>
            /// <para>If the <b>LimitFlags</b> member of the <a href="https://docs.microsoft.com/windows/desktop/api/winnt/ns-winnt-jobobject_basic_limit_information">JOBOBJECT_BASIC_LIMIT_INFORMATION</a> structure specifies the <b>JOB_OBJECT_LIMIT_JOB_MEMORY</b> value, this member specifies the limit for the virtual memory that can be committed for the job. Otherwise, this member is ignored.</para>
            /// <para><see href="https://docs.microsoft.com/windows/win32/api//winnt/ns-winnt-jobobject_extended_limit_information#members">Read more on docs.microsoft.com</see>.</para>
            /// </summary>
            internal UIntPtr JobMemoryLimit;
            /// <summary>The peak memory used by any process ever associated with the job.</summary>
            internal UIntPtr PeakProcessMemoryUsed;
            /// <summary>The peak memory usage of all processes currently associated with the job.</summary>
            internal UIntPtr PeakJobMemoryUsed;
        }
    }
}
